export const ITEM_TYPE = {
    ADD_CARD:"ADD_CARD",
    DECAREASE_CARD:"DECARE_CARD",
    REMOVE_CARD:"REMOVE_CARD",
    SHOW_MODAL: "SHOW_MODAL",
    MODAL_CARD: "MODAL_CARD",
    EMPTY_CARD:"EMPTY_CARD"
}